import mongoose from "mongoose";

const propertySchema = new mongoose.Schema(
  {
    // =====================================================
    // BASIC INFORMATION
    // =====================================================

    // Automatically generated by backend
    // land  -> "Land for Sale"
    // home  -> "Home for Sale"
    // room  -> "Room for Rent"
    // office -> "Office for Rent"
    title: {
      type: String,
      trim: true,
      default: "",
    },

    propertyType: {
      type: String,
      enum: ["land", "home", "room", "office"],
      required: true,
    },

    price: {
      type: Number,
      required: true,
      min: 0,
    },

    currency: {
      type: String,
      default: "NPR",
    },

    isNegotiable: {
      type: Boolean,
      default: false,
    },

    description: {
      type: String,
      trim: true,
      default: "",
    },

    // =====================================================
    // LOCATION
    // =====================================================

    address: {
      province: {
        type: String,
        required: true,
        trim: true,
      },

      district: {
        type: String,
        required: true,
        trim: true,
      },

      municipality: {
        type: String,
        required: true,
        trim: true,
      },

      wardNo: {
        type: Number,
        required: true,
        min: 1,
      },

      tole: {
        type: String,
        trim: true,
        default: "",
      },
    },

    // =====================================================
    // LAND INFORMATION
    // =====================================================

    landArea: {
      value: {
        type: Number,
        min: 0,
      },

      unit: {
        type: String,
        enum: [
          "sqft",
          "sqm",
          "ropani",
          "aana",
          "paisa",
          "daam",
          "bigha",
          "kattha",
          "dhur",
        ],
      },

      // Automatically calculated by backend
      // based on selected unit
      squareFeet: {
        type: Number,
        min: 0,
      },
    },

    // =====================================================
    // ROAD ACCESS
    // =====================================================

    roadAccess: {
      available: {
        type: Boolean,
        default: false,
      },

      width: {
        type: Number,
        min: 0,
      },

      widthUnit: {
        type: String,
        enum: ["ft", "m"],
        default: "ft",
      },

      type: {
        type: String,
        enum: [
          "blacktopped",
          "gravel",
          "concrete",
          "earthen",
          "paved",
          "other",
        ],
        default: "other",
      },
    },

    // =====================================================
    // HOME INFORMATION
    // =====================================================

    homeDetails: {
      // Built-up area of the house
      builtUpArea: {
        value: {
          type: Number,
          min: 0,
        },

        unit: {
          type: String,
          enum: ["sqft", "sqm"],
          default: "sqft",
        },

        // Automatically calculated by backend
        squareFeet: {
          type: Number,
          min: 0,
        },
      },

      bedrooms: {
        type: Number,
        min: 0,
      },

      bathrooms: {
        type: Number,
        min: 0,
      },

      floors: {
        type: Number,
        min: 0,
      },

      propertyAge: {
        type: Number,
        min: 0,
      },

      furnishing: {
        type: String,
        enum: [
          "fully-furnished",
          "semi-furnished",
          "unfurnished",
        ],
      },

      parking: {
        available: {
          type: Boolean,
          default: false,
        },

        capacity: {
          type: Number,
          min: 0,
        },
      },

      kitchen: {
        available: {
          type: Boolean,
          default: false,
        },

        count: {
          type: Number,
          min: 0,
        },
      },

      balcony: {
        available: {
          type: Boolean,
          default: false,
        },

        count: {
          type: Number,
          min: 0,
        },
      },

      waterSupply: {
        type: String,
        enum: [
          "municipal",
          "well",
          "boring",
          "spring",
          "other",
        ],
      },
    },

    // =====================================================
    // ROOM RENT INFORMATION
    // =====================================================

    roomDetails: {
      roomType: {
        type: String,
        enum: [
          "single",
          "double",
          "shared",
          "studio",
          "1bhk",
          "2bhk",
          "other",
        ],
      },

      floor: {
        type: Number,
        min: 0,
      },

      bathroom: {
        available: {
          type: Boolean,
          default: false,
        },

        attached: {
          type: Boolean,
          default: false,
        },
      },

      kitchen: {
        available: {
          type: Boolean,
          default: false,
        },
      },

      balcony: {
        available: {
          type: Boolean,
          default: false,
        },
      },

      furnishing: {
        type: String,
        enum: [
          "fully-furnished",
          "semi-furnished",
          "unfurnished",
        ],
      },

      wifi: {
        available: {
          type: Boolean,
          default: false,
        },
      },

      parking: {
        available: {
          type: Boolean,
          default: false,
        },
      },

      waterSupply: {
        type: String,
        enum: [
          "municipal",
          "well",
          "boring",
          "spring",
          "other",
        ],
        default: "other",
      },
    },

    // =====================================================
    // OFFICE INFORMATION
    // =====================================================

    officeDetails: {
      area: {
        value: {
          type: Number,
          min: 0,
        },

        unit: {
          type: String,
          enum: ["sqft", "sqm"],
          default: "sqft",
        },

        // Automatically calculated by backend
        squareFeet: {
          type: Number,
          min: 0,
        },
      },

      floor: {
        type: Number,
        min: 0,
      },

      numberOfRooms: {
        type: Number,
        min: 0,
      },

      meetingRoom: {
        available: {
          type: Boolean,
          default: false,
        },

        count: {
          type: Number,
          min: 0,
        },
      },

      parking: {
        available: {
          type: Boolean,
          default: false,
        },
      },

      furnishing: {
        type: String,
        enum: [
          "fully-furnished",
          "semi-furnished",
          "unfurnished",
        ],
      },
    },

    // =====================================================
    // MEDIA
    // =====================================================

    images: [
      {
        url: {
          type: String,
          required: true,
        },

        publicId: {
          type: String,
        },
      },
    ],

    video: {
      url: String,
      publicId: String,
    },

    // =====================================================
    // GEOJSON
    // =====================================================

    geometry: {
      type: {
        type: String,
        enum: ["Polygon", "Point"],
        required: true,
      },

      coordinates: {
        type: Array,
        required: true,
      },
    },

    // =====================================================
    // PROPERTY STATUS
    // =====================================================

    status: {
      type: String,
      enum: [
        "available",
        "negotiation",
        "sold",
        "rented",
        "inactive",
      ],
      default: "available",
    },

    availableFrom: {
      type: Date,
    },

    // =====================================================
    // OWNER
    // =====================================================

    owner: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // =====================================================
    // ENGAGEMENT
    // =====================================================

    views: {
      type: Number,
      default: 0,
    },

    likesCount: {
      type: Number,
      default: 0,
    },

    favoritesCount: {
      type: Number,
      default: 0,
    },

    trendingScore: {
      type: Number,
      default: 0,
    },

    isTrending: {
      type: Boolean,
      default: false,
    },

    // =====================================================
    // AI POPULARITY PREDICTION
    // =====================================================

    aiPopularityScore: {
      type: Number,
      default: null,
      min: 0,
      max: 100,
    },

    // =====================================================
    // COMMENTS
    // =====================================================

    comments: [
      {
        user: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "User",
        },

        text: {
          type: String,
          trim: true,
        },

        createdAt: {
          type: Date,
          default: Date.now,
        },
      },
    ],

    // =====================================================
    // SOLD INFORMATION
    // =====================================================

    soldAt: {
      type: Date,
      default: null,
    },
  },

  {
    timestamps: true,
  }
);

// =====================================================
// GEO INDEX
// =====================================================

propertySchema.index({
  geometry: "2dsphere",
});

export default mongoose.model("Property", propertySchema);